### ISSUE TITLE
Question : currency filter

### ISSUE THREAD

**Issue by dawadam** [lludol/investing-economic-calendar#1]
Hi, thanks for this great job !
Is it possible to filter by currency ?

**Comment by lludol** [comment]
Hello,

Thanks!

No, it's not possible for now to filter by currency because we can't do that on investing website. It's only by countries. 

But I can add that feature if you want. I just need to define which country has which currency and then add a parameter to set the currency (but it will be currency OR country, not both).

**Comment by lludol** [comment]
Hello @dawadam ,

I published a new version (0.0.3) that lets fetch news by Currencies. You have an example on the readme.
Tell me if you need something else or if there is a bug.

**Comment by dawadam** [comment]
Great !
I think "InvestingParams" is not updated, because "currencies" not exists in.

**Comment by dawadam** [comment]
Currency filter seems to work now.
Maybe the first update didn't work.

**Comment by dawadam** [comment]
An array appear on logs, like this :

```
[
  54, 34, 72, 22, 17,
  33, 10, 21, 38, 26,
   5
]
```

**Comment by dawadam** [comment]
`countries` parameter can be optional, also 'currency' parameter.

**Comment by lludol** [comment]
@dawadam Sorry for all that.
Everything should be fixed on this new 0.0.4 version.

Currencies and Countries are now optional parameters.
No more weird array of logs.
